spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # This enables discovery client integration

server:
  port: 9090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true

info:
  app:
    name: "gatewayserver"
    description: "Amrit MovieMasti Gateway Server Application"
    version: "1.0.0"

jwt:
  secret: 
