spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # This enables discovery client integration

server:
  port: 9090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka
  instance:
    preferIpAddress: true

jwt:
  secret: 
